
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

import java.util.List;
import java_cup.runtime.*;
import cup.example.Lexer;
import java.io.IOException;
import java.io.File;
import java.io.FileInputStream;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\100\000\002\002\004\000\002\037\003\000\002\037" +
    "\003\000\002\037\003\000\002\037\003\000\002\037\003" +
    "\000\002\037\003\000\002\037\003\000\002\037\004\000" +
    "\002\005\003\000\002\055\005\000\002\055\005\000\002" +
    "\056\013\000\002\056\010\000\002\056\003\000\002\022" +
    "\004\000\002\022\003\000\002\053\005\000\002\053\003" +
    "\000\002\003\003\000\002\003\003\000\002\020\005\000" +
    "\002\020\005\000\002\020\003\000\002\025\005\000\002" +
    "\025\005\000\002\025\003\000\002\024\003\000\002\024" +
    "\003\000\002\024\003\000\002\024\003\000\002\062\005" +
    "\000\002\062\005\000\002\062\003\000\002\007\003\000" +
    "\002\007\003\000\002\027\005\000\002\027\003\000\002" +
    "\030\005\000\002\030\005\000\002\030\005\000\002\030" +
    "\005\000\002\030\005\000\002\030\005\000\002\030\003" +
    "\000\002\061\012\000\002\047\006\000\002\047\010\000" +
    "\002\047\012\000\002\050\003\000\002\054\010\000\002" +
    "\057\010\000\002\057\011\000\002\057\011\000\002\041" +
    "\006\000\002\042\007\000\002\052\005\000\002\052\005" +
    "\000\002\052\005\000\002\052\003\000\002\052\003\000" +
    "\002\052\003\000\002\060\004\000\002\060\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\020\003\015\023\010\036\016\037\007\040" +
    "\006\044\013\056\020\001\002\000\006\002\ufffc\051\ufffc" +
    "\001\002\000\006\002\uffff\051\uffff\001\002\000\016\033" +
    "\033\034\026\054\043\055\036\056\041\062\030\001\002" +
    "\000\004\056\153\001\002\000\012\024\141\054\144\055" +
    "\143\062\142\001\002\000\006\002\ufffa\051\ufffa\001\002" +
    "\000\006\002\000\051\000\001\002\000\016\033\033\034" +
    "\026\054\043\055\036\056\041\062\030\001\002\000\004" +
    "\002\120\001\002\000\006\002\ufff3\051\ufff3\001\002\000" +
    "\004\056\076\001\002\000\006\002\ufffe\051\ufffe\001\002" +
    "\000\004\012\023\001\002\000\006\002\ufffd\051\ufffd\001" +
    "\002\000\006\002\ufffb\051\ufffb\001\002\000\020\023\010" +
    "\033\033\034\026\054\043\055\036\056\041\062\030\001" +
    "\002\000\006\002\ufff6\051\ufff6\001\002\000\050\002\uffe7" +
    "\005\uffe7\006\uffe7\010\uffe7\011\uffe7\013\uffe7\014\uffe7\015" +
    "\uffe7\016\uffe7\017\uffe7\020\uffe7\022\uffe7\027\uffe7\030\uffe7" +
    "\042\uffe7\050\uffe7\051\uffe7\052\uffe7\053\uffe7\001\002\000" +
    "\050\002\uffdf\005\uffdf\006\uffdf\010\uffdf\011\uffdf\013\uffdf" +
    "\014\uffdf\015\uffdf\016\uffdf\017\uffdf\020\uffdf\022\uffdf\027" +
    "\uffdf\030\uffdf\042\uffdf\050\uffdf\051\uffdf\052\uffdf\053\uffdf" +
    "\001\002\000\050\002\uffea\005\uffea\006\uffea\010\057\011" +
    "\056\013\uffea\014\uffea\015\uffea\016\uffea\017\uffea\020\uffea" +
    "\022\uffea\027\uffea\030\uffea\042\uffea\050\uffea\051\uffea\052" +
    "\uffea\053\uffea\001\002\000\050\002\uffe3\005\uffe3\006\uffe3" +
    "\010\uffe3\011\uffe3\013\uffe3\014\uffe3\015\uffe3\016\uffe3\017" +
    "\uffe3\020\uffe3\022\uffe3\027\uffe3\030\uffe3\042\uffe3\050\uffe3" +
    "\051\uffe3\052\uffe3\053\uffe3\001\002\000\016\002\ufff8\022" +
    "\ufff8\030\ufff8\051\ufff8\052\073\053\072\001\002\000\024" +
    "\002\uffe0\022\uffe0\027\uffe0\030\uffe0\042\070\050\uffe0\051" +
    "\uffe0\052\uffe0\053\uffe0\001\002\000\050\002\uffde\005\uffde" +
    "\006\uffde\010\uffde\011\uffde\013\uffde\014\uffde\015\uffde\016" +
    "\uffde\017\uffde\020\uffde\022\uffde\027\uffde\030\uffde\042\uffde" +
    "\050\uffde\051\uffde\052\uffde\053\uffde\001\002\000\050\002" +
    "\uffe4\005\uffe4\006\uffe4\010\uffe4\011\uffe4\013\uffe4\014\uffe4" +
    "\015\uffe4\016\uffe4\017\uffe4\020\uffe4\022\uffe4\027\uffe4\030" +
    "\uffe4\042\uffe4\050\uffe4\051\uffe4\052\uffe4\053\uffe4\001\002" +
    "\000\044\002\uffd5\005\053\006\054\013\uffd5\014\uffd5\015" +
    "\uffd5\016\uffd5\017\uffd5\020\uffd5\022\uffd5\027\uffd5\030\uffd5" +
    "\042\uffd5\050\uffd5\051\uffd5\052\uffd5\053\uffd5\001\002\000" +
    "\050\002\uffed\005\uffed\006\uffed\010\uffed\011\uffed\013\uffed" +
    "\014\uffed\015\uffed\016\uffed\017\uffed\020\uffed\022\uffed\027" +
    "\uffed\030\uffed\042\uffed\050\uffed\051\uffed\052\uffed\053\uffed" +
    "\001\002\000\040\002\uffdc\013\047\014\044\015\051\016" +
    "\050\017\046\020\045\022\uffdc\027\uffdc\030\uffdc\042\uffdc" +
    "\050\uffdc\051\uffdc\052\uffdc\053\uffdc\001\002\000\050\002" +
    "\uffe6\005\uffe6\006\uffe6\010\uffe6\011\uffe6\013\uffe6\014\uffe6" +
    "\015\uffe6\016\uffe6\017\uffe6\020\uffe6\022\uffe6\027\uffe6\030" +
    "\uffe6\042\uffe6\050\uffe6\051\uffe6\052\uffe6\053\uffe6\001\002" +
    "\000\050\002\uffe5\005\uffe5\006\uffe5\010\uffe5\011\uffe5\013" +
    "\uffe5\014\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\022\uffe5" +
    "\027\uffe5\030\uffe5\042\uffe5\050\uffe5\051\uffe5\052\uffe5\053" +
    "\uffe5\001\002\000\006\002\ufff7\051\ufff7\001\002\000\050" +
    "\002\uffee\005\uffee\006\uffee\010\uffee\011\uffee\013\uffee\014" +
    "\uffee\015\uffee\016\uffee\017\uffee\020\uffee\022\uffee\027\uffee" +
    "\030\uffee\042\uffee\050\uffee\051\uffee\052\uffee\053\uffee\001" +
    "\002\000\016\033\033\034\026\054\043\055\036\056\041" +
    "\062\030\001\002\000\016\033\033\034\026\054\043\055" +
    "\036\056\041\062\030\001\002\000\016\033\033\034\026" +
    "\054\043\055\036\056\041\062\030\001\002\000\016\033" +
    "\033\034\026\054\043\055\036\056\041\062\030\001\002" +
    "\000\016\033\033\034\026\054\043\055\036\056\041\062" +
    "\030\001\002\000\016\033\033\034\026\054\043\055\036" +
    "\056\041\062\030\001\002\000\044\002\uffd9\005\053\006" +
    "\054\013\uffd9\014\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9" +
    "\022\uffd9\027\uffd9\030\uffd9\042\uffd9\050\uffd9\051\uffd9\052" +
    "\uffd9\053\uffd9\001\002\000\016\033\033\034\026\054\043" +
    "\055\036\056\041\062\030\001\002\000\016\033\033\034" +
    "\026\054\043\055\036\056\041\062\030\001\002\000\050" +
    "\002\uffeb\005\uffeb\006\uffeb\010\057\011\056\013\uffeb\014" +
    "\uffeb\015\uffeb\016\uffeb\017\uffeb\020\uffeb\022\uffeb\027\uffeb" +
    "\030\uffeb\042\uffeb\050\uffeb\051\uffeb\052\uffeb\053\uffeb\001" +
    "\002\000\016\033\033\034\026\054\043\055\036\056\041" +
    "\062\030\001\002\000\016\033\033\034\026\054\043\055" +
    "\036\056\041\062\030\001\002\000\050\002\uffe9\005\uffe9" +
    "\006\uffe9\010\uffe9\011\uffe9\013\uffe9\014\uffe9\015\uffe9\016" +
    "\uffe9\017\uffe9\020\uffe9\022\uffe9\027\uffe9\030\uffe9\042\uffe9" +
    "\050\uffe9\051\uffe9\052\uffe9\053\uffe9\001\002\000\050\002" +
    "\uffe8\005\uffe8\006\uffe8\010\uffe8\011\uffe8\013\uffe8\014\uffe8" +
    "\015\uffe8\016\uffe8\017\uffe8\020\uffe8\022\uffe8\027\uffe8\030" +
    "\uffe8\042\uffe8\050\uffe8\051\uffe8\052\uffe8\053\uffe8\001\002" +
    "\000\050\002\uffec\005\uffec\006\uffec\010\057\011\056\013" +
    "\uffec\014\uffec\015\uffec\016\uffec\017\uffec\020\uffec\022\uffec" +
    "\027\uffec\030\uffec\042\uffec\050\uffec\051\uffec\052\uffec\053" +
    "\uffec\001\002\000\044\002\uffdb\005\053\006\054\013\uffdb" +
    "\014\uffdb\015\uffdb\016\uffdb\017\uffdb\020\uffdb\022\uffdb\027" +
    "\uffdb\030\uffdb\042\uffdb\050\uffdb\051\uffdb\052\uffdb\053\uffdb" +
    "\001\002\000\044\002\uffd6\005\053\006\054\013\uffd6\014" +
    "\uffd6\015\uffd6\016\uffd6\017\uffd6\020\uffd6\022\uffd6\027\uffd6" +
    "\030\uffd6\042\uffd6\050\uffd6\051\uffd6\052\uffd6\053\uffd6\001" +
    "\002\000\044\002\uffd8\005\053\006\054\013\uffd8\014\uffd8" +
    "\015\uffd8\016\uffd8\017\uffd8\020\uffd8\022\uffd8\027\uffd8\030" +
    "\uffd8\042\uffd8\050\uffd8\051\uffd8\052\uffd8\053\uffd8\001\002" +
    "\000\044\002\uffda\005\053\006\054\013\uffda\014\uffda\015" +
    "\uffda\016\uffda\017\uffda\020\uffda\022\uffda\027\uffda\030\uffda" +
    "\042\uffda\050\uffda\051\uffda\052\uffda\053\uffda\001\002\000" +
    "\044\002\uffd7\005\053\006\054\013\uffd7\014\uffd7\015\uffd7" +
    "\016\uffd7\017\uffd7\020\uffd7\022\uffd7\027\uffd7\030\uffd7\042" +
    "\uffd7\050\uffd7\051\uffd7\052\uffd7\053\uffd7\001\002\000\016" +
    "\033\033\034\026\054\043\055\036\056\041\062\030\001" +
    "\002\000\040\002\uffdd\013\047\014\044\015\051\016\050" +
    "\017\046\020\045\022\uffdd\027\uffdd\030\uffdd\042\uffdd\050" +
    "\uffdd\051\uffdd\052\uffdd\053\uffdd\001\002\000\002\001\002" +
    "\000\002\001\002\000\022\002\uffe2\022\uffe2\027\uffe2\030" +
    "\uffe2\050\uffe2\051\uffe2\052\uffe2\053\uffe2\001\002\000\022" +
    "\002\uffe1\022\uffe1\027\uffe1\030\uffe1\050\uffe1\051\uffe1\052" +
    "\uffe1\053\uffe1\001\002\000\004\021\077\001\002\000\006" +
    "\022\100\056\101\001\002\000\004\027\116\001\002\000" +
    "\010\022\ufff1\030\111\056\113\001\002\000\004\022\103" +
    "\001\002\000\004\027\104\001\002\000\004\050\105\001" +
    "\002\000\020\003\015\023\010\036\016\037\007\040\006" +
    "\044\013\056\020\001\002\000\004\051\107\001\002\000" +
    "\006\002\ufff5\051\ufff5\001\002\000\006\002\ufff9\051\ufff9" +
    "\001\002\000\004\056\114\001\002\000\004\022\ufff2\001" +
    "\002\000\004\022\uffef\001\002\000\006\030\111\056\113" +
    "\001\002\000\004\022\ufff0\001\002\000\020\003\015\023" +
    "\010\036\016\037\007\040\006\044\013\056\020\001\002" +
    "\000\006\002\ufff4\051\ufff4\001\002\000\004\002\001\001" +
    "\002\000\010\027\122\052\073\053\072\001\002\000\004" +
    "\050\123\001\002\000\020\003\015\023\010\036\016\037" +
    "\007\040\006\044\013\056\020\001\002\000\004\051\125" +
    "\001\002\000\012\002\uffce\043\130\045\127\051\uffce\001" +
    "\002\000\006\002\uffcc\051\uffcc\001\002\000\004\050\136" +
    "\001\002\000\016\033\033\034\026\054\043\055\036\056" +
    "\041\062\030\001\002\000\006\002\uffcd\051\uffcd\001\002" +
    "\000\010\050\133\052\073\053\072\001\002\000\020\003" +
    "\015\023\010\036\016\037\007\040\006\044\013\056\020" +
    "\001\002\000\004\051\135\001\002\000\006\002\uffca\051" +
    "\uffca\001\002\000\020\003\015\023\010\036\016\037\007" +
    "\040\006\044\013\056\020\001\002\000\004\051\140\001" +
    "\002\000\006\002\uffcb\051\uffcb\001\002\000\006\002\uffc3" +
    "\051\uffc3\001\002\000\006\024\uffc4\030\uffc4\001\002\000" +
    "\006\024\uffc5\030\uffc5\001\002\000\006\024\uffc6\030\uffc6" +
    "\001\002\000\006\024\146\030\147\001\002\000\006\002" +
    "\uffc2\051\uffc2\001\002\000\010\054\152\055\150\062\151" +
    "\001\002\000\006\024\uffc7\030\uffc7\001\002\000\006\024" +
    "\uffc8\030\uffc8\001\002\000\006\024\uffc9\030\uffc9\001\002" +
    "\000\004\046\154\001\002\000\004\047\155\001\002\000" +
    "\004\021\163\001\002\000\004\027\157\001\002\000\004" +
    "\050\160\001\002\000\020\003\015\023\010\036\016\037" +
    "\007\040\006\044\013\056\020\001\002\000\004\051\162" +
    "\001\002\000\006\002\uffd4\051\uffd4\001\002\000\016\033" +
    "\033\034\026\054\043\055\036\056\041\062\030\001\002" +
    "\000\006\022\167\030\166\001\002\000\006\022\uffd0\030" +
    "\uffd0\001\002\000\016\033\033\034\026\054\043\055\036" +
    "\056\041\062\030\001\002\000\004\027\uffd3\001\002\000" +
    "\006\022\172\030\171\001\002\000\016\033\033\034\026" +
    "\054\043\055\036\056\041\062\030\001\002\000\004\027" +
    "\uffd2\001\002\000\004\022\174\001\002\000\004\027\uffd1" +
    "\001\002\000\010\027\176\052\073\053\072\001\002\000" +
    "\004\050\177\001\002\000\020\003\015\023\010\036\016" +
    "\037\007\040\006\044\013\056\020\001\002\000\004\051" +
    "\201\001\002\000\006\002\uffcf\051\uffcf\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\022\011\010\037\013\054\004\055\011\056" +
    "\020\057\016\060\003\061\021\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\003\037\007\033\020\034\024" +
    "\024\025\026\027\031\030\036\062\174\001\001\000\002" +
    "\001\001\000\004\052\144\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\003\037\007\033\020\034\024\024" +
    "\025\026\027\031\030\036\062\120\001\001\000\004\011" +
    "\107\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\003\037\005\041\007\033\020\034\024\024" +
    "\025\026\027\031\030\036\060\023\062\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\003\037\007\033\020\066\024\024\025\026\001\001\000" +
    "\014\003\037\007\033\020\065\024\024\025\026\001\001" +
    "\000\014\003\037\007\033\020\064\024\024\025\026\001" +
    "\001\000\014\003\037\007\033\020\063\024\024\025\026" +
    "\001\001\000\014\003\037\007\033\020\062\024\024\025" +
    "\026\001\001\000\014\003\037\007\033\020\051\024\024" +
    "\025\026\001\001\000\002\001\001\000\012\003\037\007" +
    "\033\024\024\025\061\001\001\000\012\003\037\007\033" +
    "\024\024\025\054\001\001\000\002\001\001\000\010\003" +
    "\037\007\033\024\060\001\001\000\010\003\037\007\033" +
    "\024\057\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\003" +
    "\037\007\033\020\034\024\024\025\026\030\070\001\001" +
    "\000\002\001\001\000\004\033\074\001\001\000\004\033" +
    "\073\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\101\001\001\000\002\001\001\000" +
    "\004\053\111\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\011\010\037\105\054\004\055" +
    "\011\056\020\057\016\060\003\061\021\001\001\000\004" +
    "\011\107\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\053\114\001\001\000\002\001\001\000\022\011\010\037" +
    "\116\054\004\055\011\056\020\057\016\060\003\061\021" +
    "\001\001\000\004\011\107\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\011\010\037\123" +
    "\054\004\055\011\056\020\057\016\060\003\061\021\001" +
    "\001\000\004\011\107\001\001\000\006\041\125\042\130" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\037\007\033\020\034\024\024\025\026\027\031\030\036" +
    "\062\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\011\010\037\133\054\004\055\011\056\020\057\016" +
    "\060\003\061\021\001\001\000\004\011\107\001\001\000" +
    "\002\001\001\000\022\011\010\037\136\054\004\055\011" +
    "\056\020\057\016\060\003\061\021\001\001\000\004\011" +
    "\107\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\047\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\011\010\037\160\054\004\055" +
    "\011\056\020\057\016\060\003\061\021\001\001\000\004" +
    "\011\107\001\001\000\002\001\001\000\026\003\037\005" +
    "\164\007\033\020\034\024\024\025\026\027\031\030\036" +
    "\050\163\062\030\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\003\037\005\164\007\033\020\034\024\024" +
    "\025\026\027\031\030\036\050\167\062\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\026\003\037\005\164" +
    "\007\033\020\034\024\024\025\026\027\031\030\036\050" +
    "\172\062\030\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\011\010\037\177\054\004\055\011\056\020\057\016" +
    "\060\003\061\021\001\001\000\004\011\107\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

  ComplexSymbolFactory f = new ComplexSymbolFactory();
  symbolFactory = f;
  File file = new File("input.txt");
  FileInputStream fis = null;
  try {
    fis = new FileInputStream(file);
  } catch (IOException e) {
    e.printStackTrace();
  } 
  lexer = new Lexer(f,fis);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return lexer.next_token(); 
    }


  protected Lexer lexer;
	private Symbol s;
	public void sintax_error(Symbol s){
		this.s  = s;	
	}
	public Symbol getS (){
		return this.s;
	}




/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Comandos EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Comandos ::= atrib 
            {
              Object RESULT =null;
		int a1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int a1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando a1 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = a1;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Comandos ::= while_expr 
            {
              Object RESULT =null;
		int w1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int w1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando w1 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new BlocoWhile(w1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Comandos ::= if_expr 
            {
              Object RESULT =null;
		int i1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando i1 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new BlocoIf(i1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Comandos ::= fun_stmt 
            {
              Object RESULT =null;
		int f1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando f1 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Funcao(f1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Comandos ::= vetor 
            {
              Object RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando v1 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Vetor(v1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Comandos ::= for_stmt 
            {
              Object RESULT =null;
		int v3left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int v3right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando v3 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new BlocoFor(v3);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Comandos ::= comando 
            {
              Object RESULT =null;
		int cmdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cmdright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object cmd = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		new CompoundComando(cmd, null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Comandos ::= Comandos comando 
            {
              Object RESULT =null;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cmdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cmdright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object cmd = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		new CompoundComando(cmds, cmd);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comandos",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= logic_op 
            {
              Object RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr lp = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(lp);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // atrib ::= IDENTIFIER EQUAL expr 
            {
              Comando RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Atribuicao(e1,e2);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atrib",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // atrib ::= IDENTIFIER EQUAL vetor 
            {
              Comando RESULT =null;
		int e3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e4left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e4right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comando e4 = (Comando)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Atribuicao(e3,e4);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atrib",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // fun_stmt ::= DEF IDENTIFIER LPAREN list_params RPAREN COLON_OP IDENT Comandos DEDENT 
            {
              Comando RESULT =null;
		int lp1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lp1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object lp1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new Funcao(lp1, cmds) ;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fun_stmt",44, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // fun_stmt ::= DEF IDENTIFIER LPAREN RPAREN COLON_OP Comandos 
            {
              Comando RESULT =null;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Funcao(null, cmds);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fun_stmt",44, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // fun_stmt ::= error 
            {
              Comando RESULT =null;
		System.err.println(" Erro na definição da função \n");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fun_stmt",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // list_params ::= IDENTIFIER list_params_a 
            {
              Object RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int lp01left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lp01right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<Object> lp01 = (List<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		List<IDENTIFIER> list = new ArrayList<>();
											  list.add(r);
												RESULT = list;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_params",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // list_params ::= IDENTIFIER 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Id(e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_params",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // list_params_a ::= COMMA IDENTIFIER list_params_a 
            {
              List<Object> RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int lp01left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lp01right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<Object> lp01 = (List<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new ListaParametrosAux(lp01);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_params_a",41, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // list_params_a ::= IDENTIFIER 
            {
              List<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Id(e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_params_a",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // number_aux ::= INTEGER_LITERAL 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new IntExp(e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("number_aux",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // number_aux ::= NUMBERFLOAT_LITERAL 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Float e1 = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new FloatExp(e1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("number_aux",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // arith_op ::= arith_op PLUS T 
            {
              Object RESULT =null;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoAritmetica(aop, e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arith_op",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // arith_op ::= arith_op MINUS T 
            {
              Object RESULT =null;
		int aop01left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aop01right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object aop01 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e12left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e12right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e12 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoAritmetica(aop01, e12);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arith_op",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // arith_op ::= T 
            {
              Object RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e2;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arith_op",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // T ::= T TIMES Y 
            {
              Object RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoAritmetica(e2, e3);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("T",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // T ::= T DIVISION Y 
            {
              Object RESULT =null;
		int e7left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e7right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e7 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e8left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e8right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e8 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoAritmetica(e7, e8);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("T",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // T ::= Y 
            {
              Object RESULT =null;
		int e4left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e4right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e4;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("T",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Y ::= number_aux 
            {
              Object RESULT =null;
		int nauxleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nauxright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object naux = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = naux;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Y",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Y ::= IDENTIFIER 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Id(e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Y",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Y ::= bool_posible 
            {
              Object RESULT =null;
		int boolpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int boolpright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object boolp = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = boolp;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Y",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Y ::= STRING 
            {
              Object RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT =new StringExp(e2);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Y",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // logic_op ::= logic_op OR precedence_logic 
            {
              Expr RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr e1 = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int plleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int plright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object pl = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new PrecedenciaLogica(e1,e2,pl);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("logic_op",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // logic_op ::= logic_op AND precedence_logic 
            {
              Expr RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr e2 = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pl01left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pl01right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object pl01 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new PrecedenciaLogica(e2,e3,pl01);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("logic_op",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // logic_op ::= O 
            {
              Expr RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e1;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("logic_op",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // bool_posible ::= TRUE 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Booleanos(e1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_posible",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bool_posible ::= FALSE 
            {
              Object RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Booleanos(e2);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_posible",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // O ::= O NOT K 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int uleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object u = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e,u,e1);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("O",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // O ::= K 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e1;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("O",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // K ::= K SMALLER arith_op 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int wleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object w = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e1,w,aop);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // K ::= K LESSEQUAL arith_op 
            {
              Object RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e2,d,aop);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // K ::= K BIGGER arith_op 
            {
              Object RESULT =null;
		int e3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int qleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int qright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object q = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e3,q,aop);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // K ::= K GREATEREQUAL arith_op 
            {
              Object RESULT =null;
		int e4left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e4right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e4,a,aop);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // K ::= K NOTSAME arith_op 
            {
              Object RESULT =null;
		int e5left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e5right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e5 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object m = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e5,m,aop);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // K ::= K EQUALTWO arith_op 
            {
              Object RESULT =null;
		int e6left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e6right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e6 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int zleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int zright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object z = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new OperacaoLogica(e6,z,aop);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // K ::= arith_op 
            {
              Object RESULT =null;
		int aopleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aopright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object aop = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = aop;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("K",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // for_stmt ::= FOR IDENTIFIER IN range_stmt COLON_OP IDENT Comandos DEDENT 
            {
              Comando RESULT =null;
		int e5left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int e5right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Object e5 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int rsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int rsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object rs = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new BlocoFor(e5, rs, cmds, null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",47, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // range_stmt ::= RANGE LPAREN range_values RPAREN 
            {
              Object RESULT =null;
		int rvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object rv = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new Range(rv,null,null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("range_stmt",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // range_stmt ::= RANGE LPAREN range_values COMMA range_values RPAREN 
            {
              Object RESULT =null;
		int rvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int rvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object rv = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int rv01left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rv01right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object rv01 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new Range(rv,rv01,null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("range_stmt",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // range_stmt ::= RANGE LPAREN range_values COMMA range_values COMMA range_values RPAREN 
            {
              Object RESULT =null;
		int rvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int rvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object rv = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int rv01left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int rv01right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object rv01 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int rv02left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rv02right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object rv02 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new Range(rv,rv01,rv02);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("range_stmt",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // range_values ::= expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e1;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("range_values",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // while_expr ::= WHILE logic_op COLON_OP IDENT Comandos DEDENT 
            {
              Comando RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Expr lp = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new BlocoWhile(lp, cmds);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_expr",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // if_expr ::= IF logic_op COLON_OP IDENT Comandos DEDENT 
            {
              Comando RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Expr lp = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new BlocoIf(lp, cmds);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_expr",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // if_expr ::= IF logic_op COLON_OP IDENT Comandos DEDENT elif_stmt 
            {
              Comando RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Expr lp = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int elifstmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elifstmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object elifstm = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new BlocoIf(lp, null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_expr",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // if_expr ::= IF logic_op COLON_OP IDENT Comandos DEDENT else_stmt 
            {
              Comando RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Expr lp = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int elstmtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elstmtright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object elstmt = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new BlocoIf(lp,cmds,elstmt,lp );
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_expr",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // else_stmt ::= ELSE IDENT Comandos DEDENT 
            {
              Object RESULT =null;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new BlocoElse(cmds, null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_stmt",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // elif_stmt ::= ELIF logic_op IDENT Comandos DEDENT 
            {
              Object RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Expr lp = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cmdsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cmdsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object cmds = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new BlocoElif(lp, cmds, null);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("elif_stmt",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // aux_vetor ::= aux_vetor COMMA INTEGER_LITERAL 
            {
              List<Object> RESULT =null;
		int auvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int auvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<Object> auv = (List<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		auv.add(e1);
													RESULT = auv;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux_vetor",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // aux_vetor ::= aux_vetor COMMA STRING 
            {
              List<Object> RESULT =null;
		int auvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int auvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<Object> auv = (List<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		auv.add(e2);
													RESULT = auv;;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux_vetor",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // aux_vetor ::= aux_vetor COMMA NUMBERFLOAT_LITERAL 
            {
              List<Object> RESULT =null;
		int auvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int auvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<Object> auv = (List<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Float e3 = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		auv.add(e3);
													RESULT = auv;;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux_vetor",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // aux_vetor ::= INTEGER_LITERAL 
            {
              List<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		List<Object>list = new ArrayList<>();
								list.add(e1);
								RESULT = list;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux_vetor",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // aux_vetor ::= NUMBERFLOAT_LITERAL 
            {
              List<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Float e1 = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		List<Object>list = new ArrayList<>();
								list.add(e1);
								RESULT = list;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux_vetor",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // aux_vetor ::= STRING 
            {
              List<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		List<Object>list = new ArrayList<>();
								list.add(e1);
								RESULT = list;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux_vetor",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // vetor ::= L_BRACKET R_BRACKET 
            {
              Comando RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // vetor ::= L_BRACKET aux_vetor R_BRACKET 
            {
              Comando RESULT =null;
		int auvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int auvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<Object> auv = (List<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = auv;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
