
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int L_KEY = 19;
  public static final int UMINUS = 5;
  public static final int SCORE = 23;
  public static final int SMALLER = 12;
  public static final int COMENTARIOS = 46;
  public static final int LPAREN = 15;
  public static final int SEMI = 2;
  public static final int FOR = 29;
  public static final int MINUS = 4;
  public static final int RPAREN = 16;
  public static final int NUMBERFLOAT_LITERAL = 43;
  public static final int AND = 41;
  public static final int NOT = 32;
  public static final int SEMICOLON = 24;
  public static final int RANGE = 37;
  public static final int LESSEQUAL = 14;
  public static final int OR = 40;
  public static final int IN = 36;
  public static final int RESERVED_WORDS = 45;
  public static final int COMMA = 22;
  public static final int R_KEY = 20;
  public static final int PLUS = 3;
  public static final int IF = 34;
  public static final int COLON_OP = 21;
  public static final int R_BRACKET = 18;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int EQUAL = 8;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int COMENTARIO = 47;
  public static final int GLOBAL = 31;
  public static final int IDENT = 38;
  public static final int BIGGER = 11;
  public static final int GREATEREQUAL = 13;
  public static final int NOTSAME = 10;
  public static final int TIMES = 6;
  public static final int ELSE = 35;
  public static final int WHILE = 30;
  public static final int DEDENT = 39;
  public static final int STRING = 48;
  public static final int DEF = 28;
  public static final int FALSE = 25;
  public static final int L_BRACKET = 17;
  public static final int EQUALTWO = 9;
  public static final int DIVISION = 7;
  public static final int ELIF = 33;
  public static final int IDENTIFIER = 44;
  public static final int INTEGER_LITERAL = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "DIVISION",
  "EQUAL",
  "EQUALTWO",
  "NOTSAME",
  "BIGGER",
  "SMALLER",
  "GREATEREQUAL",
  "LESSEQUAL",
  "LPAREN",
  "RPAREN",
  "L_BRACKET",
  "R_BRACKET",
  "L_KEY",
  "R_KEY",
  "COLON_OP",
  "COMMA",
  "SCORE",
  "SEMICOLON",
  "FALSE",
  "TRUE",
  "RETURN",
  "DEF",
  "FOR",
  "WHILE",
  "GLOBAL",
  "NOT",
  "ELIF",
  "IF",
  "ELSE",
  "IN",
  "RANGE",
  "IDENT",
  "DEDENT",
  "OR",
  "AND",
  "INTEGER_LITERAL",
  "NUMBERFLOAT_LITERAL",
  "IDENTIFIER",
  "RESERVED_WORDS",
  "COMENTARIOS",
  "COMENTARIO",
  "STRING"
  };
}

